# Generated by Django 3.0.14 on 2023-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/', verbose_name='imagen')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
